name: Build Jukebox

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
            build-type: RelWithDebInfo
          - name: macOS
            os: macos-latest
          - name: Android32
            os: ubuntu-22.04
            target: Android32
          - name: Android64
            os: ubuntu-22.04
            target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.config.target }}

      - name: Build
        uses: geode-sdk/build-geode-mod@main
        with:
          export-pdb: true
          combine: true
          target: ${{ matrix.config.target }}
          build-config: ${{ matrix.config.build-type || 'Release' }}

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Combine builds
        uses: geode-sdk/build-geode-mod/combine@main
        id: build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
